server:
  port: 8080

logging:
  level:
    root: debug

spring:
  #  dubbo中的服务名称
  dubbo:
    application: user-web
    registry:
      #      zookeeper注册中心的地址
      address: 192.168.125.131:2181
      #     zookeeper的通讯协议的名称
      protocol: zookeeper
    #       dubbo通讯协议的名称
    protocol:
      name: dubbo
    #       dubbo的服务扫描路劲
    base-package: com.atguigu.gmall
    # 设置超时时间
    consumer:
      timeout: 6000
      # 检查是否服务存在
      check: false